default:
  image: $CI_REGISTRY/protonvpn/android/android-app-new:latest

before_script:
  - export JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=$( echo ${http_proxy##http://} | cut -d':' -f1 ) -Dhttp.proxyPort=$( echo ${http_proxy##http://} | cut -d':' -f2 ) -Dhttps.proxyHost=$( echo ${https_proxy##http://} | cut -d':' -f1 ) -Dhttps.proxyPort=$( echo ${https_proxy##http://} | cut -d':' -f2 ) -Dhttp.nonProxyHosts=\"$( echo $no_proxy | tr ',' '|' )\""
  #  - echo -e "y\ny\ny\ny\ny\ny\ny\ny\n" | $ANDROID_HOME/tools/bin/sdkmanager --licenses --proxy=http --proxy_host=$( echo ${https_proxy##http://} | cut -d':' -f1 ) --proxy_port=$( echo ${https_proxy##http://} | cut -d':' -f2 )
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export VERSION_NAME=$(grep -E "versionName " buildSrc/src/main/kotlin/ProtonMail.kt | awk '{print $5}' | sed s/\"//g)
  - export VERSION_CODE=$(grep -E "versionCode " buildSrc/src/main/kotlin/ProtonMail.kt | awk '{print $5}' | sed s/\"//g)
  - echo "App version name ${VERSION_NAME}"
  - echo "App version name ${VERSION_CODE}"
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle
    - '**/build'
    - '**/**/build'
    - '**/**/**/build'

stages:
  - manual-release
  - analyze
  - build
  - test
  - bot-i18n
  - bot-release

#####################
.detekt-analysis-common:
  stage: analyze
  tags:
    - medium
  script:
    - ./gradlew multiModuleDetekt
  artifacts:
    reports:
      codequality: config/detekt/reports/mergedReport.json

detekt analysis release:
  extends: .detekt-analysis-common
  allow_failure: true
  only:
    - release
    - prerelease
    - tags
  except:
    - schedules

detekt analysis:
  extends: .detekt-analysis-common
  only:
    refs:
      - merge_requests
      - branches
      - schedules
  except:
    - release
    - prerelease
    - tags

.build-debug-common:
  stage: build
  only:
    - merge_requests
    - branches
    - schedules
  tags:
    - large
  script:
    - ./gradlew assembleBetaDebug
    - ./gradlew assembleBetaDebugAndroidTest
  artifacts:
    expire_in: 1 week
    paths:
      - app/build/outputs/apk

build debug:
  extends: .build-debug-common
  needs:
    - job: detekt analysis
  except:
    - develop
    - release
    - prerelease
    - tags
    - schedules

build debug develop:
  extends: .build-debug-common
  needs:
    - job: detekt analysis
  only:
    - develop
  script:
    - ./gradlew clean
    - ./gradlew assembleBetaDebug
    - ./gradlew assembleBetaDebugAndroidTest

build debug uitests:
  extends: .build-debug-common
  only:
    - schedules

build debug release:
  extends: .build-debug-common
  only:
    - release
    - prerelease
    - tags

build prerelease:
  stage: build
  except:
    - schedules
  only:
    - prerelease
    - tags
  tags:
    - large
  script:
    - ./gradlew clean
    - ./gradlew assemblePlaystoreReleasePlayStore
  artifacts:
    expire_in: 3 week
    paths:
      - app/build/outputs

build release:
  stage: build
  except:
    - schedules
  only:
    - releases
  tags:
    - large
  script:
    - ./gradlew clean
    - ./gradlew assemblePlaystoreReleasePlayStore
  artifacts:
    expire_in: 4 week
    paths:
      - app/build/outputs


.unit-tests-common:
  stage: test
  only:
    - merge_requests
    - branches
  except:
    - schedules
  tags:
    - large
  script:
    - ./gradlew -Pci --console=plain allTest

unit tests:
  extends: .unit-tests-common
  needs:
    - job: build debug
  except:
    - develop
    - release
    - prerelease
    - tags
    - schedules

unit tests develop:
  extends: .unit-tests-common
  needs:
    - job: build debug develop
  only:
    - develop

unit tests release:
  extends: .unit-tests-common
  only:
    - release
    - prerelease
    - tags


.firebase-tests-common:
  stage: test
  only:
    - merge_requests
    - branches
  except:
    - schedules
  tags:
    - medium
  script:
    - wget --quiet --output-document=/tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
    - mkdir -p /opt
    - tar zxf /tmp/google-cloud-sdk.tar.gz --directory /opt
    - /opt/google-cloud-sdk/install.sh --quiet
    - source /opt/google-cloud-sdk/path.bash.inc
    - gcloud components update
    - echo $CLOUD_PROJECT_ID_MAIL
    - gcloud config set project $CLOUD_PROJECT_ID_MAIL
    - echo $SERVICE_ACCOUNT_MAIL > /tmp/service-account.json
    - gcloud auth activate-service-account --key-file /tmp/service-account.json
    - gcloud --quiet firebase test android run
      --app app/build/outputs/apk/beta/debug/ProtonMail-Android-${VERSION_NAME}-beta-debug.apk
      --test app/build/outputs/apk/androidTest/beta/debug/ProtonMail-Android-${VERSION_NAME}-beta-debug-androidTest.apk
      --device model=Pixel2,version=28
      --test-targets "class ch.protonmail.android.uitests.tests.suites.SmokeSuite"
      --use-orchestrator
      --num-flaky-test-attempts=1
      --timeout 45m

firebase tests:
  extends: .firebase-tests-common
  needs:
    - job: build debug
  except:
    - develop
    - release
    - prerelease
    - tags
    - schedules

firebase tests develop:
  extends: .firebase-tests-common
  needs:
    - job: build debug develop
  only:
    - develop

firebase tests release:
  extends: .firebase-tests-common
  only:
    - release
    - prerelease
    - tags


firebase feature tests:
  stage: test
  needs:
    - job: build debug uitests
  rules:
    - if: '$TEST_TYPE == "feature" || $TEST_TYPE == "regression"'
  tags:
    - medium
  variables:
    MODEL: ""
  script:
    - if [ -z ${DEVICE_MODEL+x} ]; then MODEL="Pixel2"; else MODEL=$DEVICE_MODEL; fi
    - wget --quiet --output-document=/tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
    - mkdir -p /opt
    - tar zxf /tmp/google-cloud-sdk.tar.gz --directory /opt
    - /opt/google-cloud-sdk/install.sh --quiet
    - source /opt/google-cloud-sdk/path.bash.inc
    - gcloud components update --quiet
    - echo $CLOUD_PROJECT_ID_MAIL
    - gcloud config set project $CLOUD_PROJECT_ID_MAIL --quiet
    - echo $SERVICE_ACCOUNT_MAIL > /tmp/service-account.json
    - gcloud auth activate-service-account --key-file /tmp/service-account.json --quiet
    - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - gcloud beta firebase test android run
      --quiet
      --app app/build/outputs/apk/beta/debug/ProtonMail-Android-${VERSION_NAME}-beta-debug.apk
      --test app/build/outputs/apk/androidTest/beta/debug/ProtonMail-Android-${VERSION_NAME}-beta-debug-androidTest.apk
      --device model=$MODEL,version=$API_LEVEL
      --test-targets "class ch.protonmail.android.uitests.tests.$TEST_CLASS"
      --use-orchestrator
      --num-flaky-test-attempts=1
      --timeout 45m
      --client-details testType=$TEST_TYPE,testSuite=$TEST_CLASS,commitBranch=$CI_COMMIT_BRANCH,gitlabJobUrl=$CI_JOB_URL

include:
  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'

  - project: 'agarroux/publish-github'
    ref: master
    file: '/jobs/release.gitlab-ci.yml'

i18n-sync-crowdin:
  stage: bot-i18n
  variables:
    I18N_SYNC_CROWDIN_PROJECT: 'android-mail'
  extends: .i18n-sync-crowdin-shared
  except:
    variables:
      - $TEST_TYPE == "feature" || $TEST_TYPE == "regression"

i18n-commit-locales:
  stage: bot-i18n
  variables:
    I18N_COMMIT_CROWDIN_PROJECT: 'android-mail'
  extends: .i18n-commit-locales-shared
  except:
    variables:
      - $TEST_TYPE == "feature" || $TEST_TYPE == "regression"

release-publish-github:
  stage: manual-release
  when: 'manual'
  variables:
    RELEASE_SYNC_PUBLIC_URL: git@github.com:ProtonMail/proton-mail-android.git
    RELEASE_SYNC_TO_BRANCH: 'release'
    RELEASE_SYNC_FROM_BRANCH: 'release'
  extends: .release-sync-commit-shared
  tags:
    - small

release-publish-github-tags:
  needs:
    - job: build prerelease
      artifacts: true
  stage: bot-release
  variables:
    RELEASE_SYNC_PUBLIC_URL: git@github.com:ProtonMail/proton-mail-android.git
    RELEASE_SYNC_TO_BRANCH: 'release'
    RELEASE_SYNC_FROM_BRANCH: 'release'
  extends: .release-sync-tags-shared
  tags:
    - small

publish-github:
  stage: bot-release
  needs:
    - job: build prerelease
      artifacts: true
  variables:
    RELEASE_APP: android-mail
    RELEASE_GITHUB_REPOSITORY: ProtonMail/proton-mail-android
    RELEASE_GITHUB_BRANCH: 'release'
  extends: .release-make-release
  tags:
    - small

check for fixups:
  stage: analyze
  only:
    - merge_requests
  script:
    - git fetch origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - git fetch origin "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - git log --pretty=%s "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME..origin/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" | awk '$0 ~ /^fixup/ {find = 1}; END { exit find }'
